#!/bin/bash
# Complete backend setup and configuration

set -e

REGION="eu-north-1"
BUCKET_NAME="lib-mgmt-tf-state-$(date +%s)"
DYNAMODB_TABLE="lib-mgmt-terraform-locks"

echo "=========================================="
echo "Setting up Terraform Backend"
echo "=========================================="

# Create S3 bucket (LocationConstraint required for regions other than us-east-1)
echo "1. Creating S3 bucket: $BUCKET_NAME"
if [ "$REGION" = "us-east-1" ]; then
  aws s3api create-bucket --bucket $BUCKET_NAME --region $REGION
else
  aws s3api create-bucket \
    --bucket $BUCKET_NAME \
    --region $REGION \
    --create-bucket-configuration LocationConstraint=$REGION
fi

# Enable versioning
echo "2. Enabling versioning..."
aws s3api put-bucket-versioning \
  --bucket $BUCKET_NAME \
  --versioning-configuration Status=Enabled

# Enable encryption
echo "3. Enabling encryption..."
aws s3api put-bucket-encryption \
  --bucket $BUCKET_NAME \
  --server-side-encryption-configuration '{
    "Rules": [{
      "ApplyServerSideEncryptionByDefault": {
        "SSEAlgorithm": "AES256"
      }
    }]
  }'

# Block public access
echo "4. Blocking public access..."
aws s3api put-public-access-block \
  --bucket $BUCKET_NAME \
  --public-access-block-configuration \
    BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true

# Create DynamoDB table
echo "5. Creating DynamoDB table: $DYNAMODB_TABLE"
aws dynamodb create-table \
  --table-name $DYNAMODB_TABLE \
  --attribute-definitions AttributeName=LockID,AttributeType=S \
  --key-schema AttributeName=LockID,KeyType=HASH \
  --billing-mode PAY_PER_REQUEST \
  --region $REGION 2>/dev/null || echo "Table already exists"

# Wait for table
echo "6. Waiting for DynamoDB table..."
aws dynamodb wait table-exists --table-name $DYNAMODB_TABLE

# Create backend.tf
echo "7. Creating backend.tf..."
cat > terraform/backend.tf << EOF
# Terraform Backend Configuration
# Auto-generated by configure-backend.sh

terraform {
  backend "s3" {
    bucket         = "$BUCKET_NAME"
    key            = "production/terraform.tfstate"
    region         = "$REGION"
    encrypt        = true
    dynamodb_table = "$DYNAMODB_TABLE"
  }
}
EOF

echo ""
echo "=========================================="
echo "✓ Backend Setup Complete!"
echo "=========================================="
echo ""
echo "S3 Bucket: $BUCKET_NAME"
echo "DynamoDB Table: $DYNAMODB_TABLE"
echo "Backend file: terraform/backend.tf"
echo ""
echo "Next steps:"
echo "1. cd terraform"
echo "2. terraform init -migrate-state"
echo "3. terraform apply"
echo ""

# Save to GitHub secrets instructions
cat > github-backend-secrets.txt << EOF
Add these to GitHub Secrets for the pipeline:

TF_STATE_BUCKET=$BUCKET_NAME
TF_STATE_DYNAMODB_TABLE=$DYNAMODB_TABLE
EOF

echo "GitHub secrets saved to: github-backend-secrets.txt"
